sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - travis_test

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.7.3
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk

before_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "5.6" || "$TRAVIS_PHP_VERSION" == "7.0" ]]; then
      composer remove phpunit/phpunit "^7"
      composer require phpunit/phpunit "^5"
    fi
  - composer install --prefer-dist --no-interaction
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      ./vendor/bin/phpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      ./vendor/bin/phpcs --extensions=php --ignore=*/node_modules/*,*/vendor/*
    fi
